version: '3'

services:
  todotests:
    build: ./todo-app/tests
    depends_on:
      - todofront
      - todoback
    environment:
      - FRONT_HOST=todofront
    #...
  todofront:
    build: ./todo-app/front-end
    ports:
      - 3000:3000
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback
    #...
  todoback:
    build: ./todo-app/back-end
    ports:
      - 3001:3001
    #...



